// <auto-generated />
using System;
using DSV_BackEnd_DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DSV_BackEnd_DataLayer.Migrations
{
    [DbContext(typeof(DSVDatabaseContext))]
    [Migration("20210630095150_Added image model migration")]
    partial class Addedimagemodelmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DSV_BackEnd_DataLayer.DataModel.Article", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Editor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousStorageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("DSV_BackEnd_DataLayer.DataModel.Book", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Editor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousStorageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicationLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubLevelTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("DSV_BackEnd_DataLayer.DataModel.Image", b =>
                {
                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ArticleAssetID")
                        .HasColumnType("int");

                    b.Property<string>("Base64EncodedImageData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BookAssetID")
                        .HasColumnType("int");

                    b.HasKey("ImageName");

                    b.HasIndex("ArticleAssetID");

                    b.HasIndex("BookAssetID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("DSV_BackEnd_DataLayer.DataModel.Image", b =>
                {
                    b.HasOne("DSV_BackEnd_DataLayer.DataModel.Article", null)
                        .WithMany("Images")
                        .HasForeignKey("ArticleAssetID");

                    b.HasOne("DSV_BackEnd_DataLayer.DataModel.Book", null)
                        .WithMany("Images")
                        .HasForeignKey("BookAssetID");
                });

            modelBuilder.Entity("DSV_BackEnd_DataLayer.DataModel.Article", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("DSV_BackEnd_DataLayer.DataModel.Book", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
